{
 "title": "LaravelS Service Monitor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(swoole_connection_num{application=\"$application\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application, method)",
     "legendFormat": "{{application}}-{{method}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application)",
     "legendFormat": "{{application}}"
    },
    {
     "expr": "sum(rate(swoole_request_count{application=\"$application\"}[1m])) by (application)",
     "legendFormat": "{{application}}-Swoole"
    }
   ]
  },
  {
   "title": "Top RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(rate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Total 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(rate(http_server_requests_seconds_count{application=\"$application\",status=~\"5..\"}[1m])) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "5xx Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(rate(http_server_requests_seconds_count{application=\"$application\",status=~\"5..\"}[1m])) by (application, method, uri) / sum(rate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Avg Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(rate(http_server_requests_seconds_sum{application=\"$application\"}[1m])) by (application, method, uri)/sum(rate(http_server_requests_seconds_count{application=\"$application\"}[1m])) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Max Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk(20, max(http_server_requests_seconds_max{application=\"$application\"}) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "swoole_request_count{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Top Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(http_server_requests_seconds_count{application=\"$application\"}) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Bottom Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk(10, sum(http_server_requests_seconds_count{application=\"$application\"}) by (application, method, uri))",
     "legendFormat": "{{application}}-{{method}}-{{uri}}"
    }
   ]
  },
  { "title": "CPU/Memory Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} 1m"
    },
    {
     "expr": "system_load_average_5m{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} 5m"
    },
    {
     "expr": "system_load_average_15m{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} 15m"
    },
    {
     "expr": "swoole_cpu_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} CPU"
    }
   ]
  },
  {
   "title": "APCu Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "apcu_seg_size{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} Total"
    },
    {
     "expr": "apcu_avail_mem{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} Available"
    }
   ]
  },
  {
   "title": "Memory Usage(Worker)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(swoole_process_memory_usage{application=\"$application\",instance=~\"$instance\",process_type=\"worker\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} Current Used"
    },
    {
     "expr": "sum(swoole_process_memory_real_usage{application=\"$application\",instance=~\"$instance\",process_type=\"worker\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} System Allocated"
    }
   ]
  },
  {
   "title": "Memory Usage(Task Worker)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(swoole_process_memory_usage{application=\"$application\",instance=~\"$instance\",process_type=\"task\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} Current Used"
    },
    {
     "expr": "sum(swoole_process_memory_real_usage{application=\"$application\",instance=~\"$instance\",process_type=\"task\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} System Allocated"
    }
   ]
  },
  {
   "title": "Memory Usage(Timer)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(swoole_process_memory_usage{application=\"$application\",instance=~\"$instance\",process_type=\"timer\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} Current Used"
    },
    {
     "expr": "sum(swoole_process_memory_real_usage{application=\"$application\",instance=~\"$instance\",process_type=\"timer\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}} System Allocated"
    }
   ]
  },
  { "title": "Swoole Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Worker Num",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "swoole_worker_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} Total"
    },
    {
     "expr": "swoole_idle_worker_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} Idle"
    }
   ]
  },
  {
   "title": "Task Worker Num",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "swoole_task_worker_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} Total"
    },
    {
     "expr": "swoole_task_idle_worker_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} Idle"
    },
    {
     "expr": "swoole_tasking_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}} Tasking"
    }
   ]
  },
  {
   "title": "Connection Num",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "swoole_connection_num{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "dtdhms" }
   ],
   "targets": [
    {
     "expr": "time()-swoole_start_time{application=\"$application\",instance=~\"$instance\"}",
     "legendFormat": "{{application}}-{{instance}}"
    }
   ]
  },
  { "title": "GC Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "GC Status(Worker)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(swoole_process_gc_runs{application=\"$application\",instance=~\"$instance\",process_type=\"worker\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}}  Runs"
    },
    {
     "expr": "sum(swoole_process_gc_collected{application=\"$application\",instance=~\"$instance\",process_type=\"worker\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}}  Collected"
    },
    {
     "expr": "sum(swoole_process_gc_threshold{application=\"$application\",instance=~\"$instance\",process_type=\"worker\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}}  Threshold"
    },
    {
     "expr": "sum(swoole_process_gc_roots{application=\"$application\",instance=~\"$instance\",process_type=\"worker\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}}  Roots"
    }
   ]
  },
  {
   "title": "GC Status(Task Worker)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(swoole_process_gc_runs{application=\"$application\",instance=~\"$instance\",process_type=\"task\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}}  Runs"
    },
    {
     "expr": "sum(swoole_process_gc_collected{application=\"$application\",instance=~\"$instance\",process_type=\"task\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}}  Collected"
    },
    {
     "expr": "sum(swoole_process_gc_threshold{application=\"$application\",instance=~\"$instance\",process_type=\"task\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}}  Threshold"
    },
    {
     "expr": "sum(swoole_process_gc_roots{application=\"$application\",instance=~\"$instance\",process_type=\"task\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}}  Roots"
    }
   ]
  },
  {
   "title": "GC Status(Timer)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(swoole_process_gc_runs{application=\"$application\",instance=~\"$instance\",process_type=\"timer\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}}  Runs"
    },
    {
     "expr": "sum(swoole_process_gc_collected{application=\"$application\",instance=~\"$instance\",process_type=\"timer\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}}  Collected"
    },
    {
     "expr": "sum(swoole_process_gc_threshold{application=\"$application\",instance=~\"$instance\",process_type=\"timer\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}}  Threshold"
    },
    {
     "expr": "sum(swoole_process_gc_roots{application=\"$application\",instance=~\"$instance\",process_type=\"timer\"}) by (application, instance)",
     "legendFormat": "{{application}}-{{instance}}  Roots"
    }
   ]
  }
 ]
}